language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
addons:
  ssh_known_hosts: projects.rapit.pw
after_success:
- openssl aes-256-cbc -K $encrypted_97ea47a6a27b_key -iv $encrypted_97ea47a6a27b_iv
  -in deploy-key.enc -out deploy-key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy-key
- ssh-add deploy-key
- scp target/likes-*.jar deploy@projects.rapit.pw:/var/www/likes/likes.jar
- ssh deploy@projects.rapit.pw 'mv /var/www/likes/target /var/www/likes/target-`date
  +%Y-%m-%d.%H:%M:%S`'
- ssh deploy@projects.rapit.pw 'sudo /bin/systemctl restart likesapp.service'
notifications:
  slack:
    secure: dQ7gXdtew4kFWKOZWKnDiP+N9tcqhOiAAJOvZNEEVZr8dbc+SSi3FRnSC9tb0aPuYuqKhd8ZdatqtVadTxS3kCmZNBKvFfb8oX9kwfNDLeHYvfX5jcIggcH1d23vazzFr61LrWvi3+8UbMeXMEH/3tUnDCTSuaYFXNjVmCL2pyHPXaXnNgjeuDZeqmUaWcauAVCYYwGyGJ6srgv8UgJGdhqegqJwmYhHJ0ynPVRCh3CfOPwNpO1xOvoTYRlY0VdN4VddPPFA6pyaBnARDjz/UFObubK5hOQaFPz+vJkaVhCOGdditzICDzDN/I9CtkWbsJSWypJ5TtwzXKZVnojNVFf3x1ziT1nwMWc1umNSHQxPG6nmAWcAbHmYGUoFh2y6kdfD+SDCo8zgRR/KhllBCKdg/aCXBPQqw5STfYhpye25/XeCq4boSE+pE7Gf5YeUzjqfDW/y/vQX7seTo3M9h63O4QzqesJVvZPuyzeL+swCG0AVh3P8wR5yj/eUAIOs/CspqiVOR4t+OlyfKY/ULcGN/u7fAtKPOFncapEKUiOKZJd7DSaLJuimxk2hxSAEf199aZ5tbTtJPcVm8XhBnfHplPUB6mukACMDZZeh1RfNJGTr6yfomivikYBgRp/mYJccTzE5xNQXBtjNmkfMzsJt0DCLANTv9nmdqmbUzbo=
