language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
addons:
  ssh_known_hosts: projects.rapit.pw
after_success:
- openssl aes-256-cbc -K $encrypted_97ea47a6a27b_key -iv $encrypted_97ea47a6a27b_iv -in deploy-key.enc -out deploy-key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy-key
- ssh-add deploy-key
- scp target/likes-*.jar deploy@projects.rapit.pw:/var/www/likes/likes.jar
- ssh deploy@projects.rapit.pw 'mv /var/www/likes/target /var/www/likes/target-`date +%Y-%m-%d.%H:%M:%S`'
- ssh deploy@projects.rapit.pw 'sudo /bin/systemctl restart likesapp.service'
